### ISSUE TITLE
"Hysteresis Threshold" displays an error message

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#11]
See attached screenshot.

![bildschirmfoto von 2015-03-25 14 47 10](https://cloud.githubusercontent.com/assets/7261570/6825892/03549d62-d2fe-11e4-9e8d-6992c0034a87.png)

**Comment by schmk2** [comment]
Fixed by e06207a43aecea48ebfa9cbe026f051227aa7749
