### ISSUE TITLE
Check for update fails on fetching from the old server (imageplay.io)

### ISSUE THREAD

**Issue by czerwinskilukasz1** [cpvrlab/ImagePlay#120]
OS: noticed on Windows, but the source code clearly shows that it's an issue for all OSs (https://github.com/cpvrlab/ImagePlay/blob/29b056045b2fe22294d1c04ef84043a6767225c0/ImagePlay/ImagePlay.pro#L60).

<img width="215" alt="2020-04-13 08_56_04-ImagePlay 6 1 0" src="https://user-images.githubusercontent.com/12752520/79099820-4a4dc100-7d65-11ea-8c48-c04cb9807c68.png">

**Comment by hudrima1** [comment]
Hi Lukasz,
thanks for the message. I changed the URL to the github pages page: http://cpvrlab.github.io/ImagePlay/ <http://cpvrlab.github.io/ImagePlay/>
Regards
Marcus

**Comment by czerwinskilukasz1** [comment]
Hi Marcus,
Thank you, it works now! 
I think we can close this ticket.
