### ISSUE TITLE
[Windows] Qmake doesn't copy images/sequence to the application directory

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#16]
The "sequence" subdirectory is not properly copied to the "images" directory in the applications build location. This seems to be a drawback of ${QMAKE_COPY}; but switching to ${QMAKE_COPY_DIR} doesn't fix the problem.
A possibility would be to use robocopy instead, since the copying is already done per platform anyway.

**Comment by schmk2** [comment]
This works under Windows:
$${QMAKE_COPY_DIR} media\\images ..\\_bin\\$$CONFIGURATION\\$$PLATFORM\\images\\

Note the additional and missing backslashes at the end of the path.
