### ISSUE TITLE
High frequency generation of IPLProcessMessage instances causes a crash

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#17]
Steps to reproduce:

- Add a high-frequency element "Load Sequence" or "Capture Camera"
- Connect it to "Binarize Otsu"
- Enable preview and let it run for a while

- The application crashes somewhere around IPLProcess.cpp:277 (addMessage or resetMessages) with a Segfault within a vector re-allocation.
- The higher the frequency of the source is, the faster the error seems to occur.

**Comment by mfrischknecht** [comment]
"Binarize Unimodal" and "Binarize Entropy" show the same effect, whereas for "Binarize k-Means" it doesn't seem to occur.

**Comment by schmk2** [comment]
Fixed by 0c7e8041ad9629e3c8322ddb296f46d34f5647f1
