### ISSUE TITLE
Preview sometimes ignores updates during re-calculation.

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#2]
For some algorithms, the preview doesn't recognize any changes to the parameters that happen during the recalculation of the whole pipeline. For example, this is the case when moving the "Wavelength" slider for the "Synthesize Image" element.

Reproduction:
- Create a pipeline that takes some time to re-evaluate
- Include at least one "Synthesize Image" element
- Alter it's wavelength using the slider
- If you're quick enough (i.e. the pipeline is slow enough), updates to the slider will fall into the recalculation time of a previous update and be ignored

![update](https://cloud.githubusercontent.com/assets/7261570/6801893/d370c530-d22b-11e4-80a0-a58545ac56ee.png)

**Comment by schmk2** [comment]
It is only partially fixed. Updates don't propagate properly through the graph.

**Comment by l00mi** [comment]
Work was done to fix this bug.

We can not guarantee that previews works in all situations. If you find a bug please open an new specific issue.
