### ISSUE TITLE
"Triangle Segmentation" crashes

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#20]
- Create a "Load Image" element, open "lena_rgb.png"
- Connect it to a "Triangle Segmentation" element
- Enable the preview

- The application crashes at IPLProcess.cpp:279
- This might be a duplicate of https://github.com/cpvrlab/ImagePlay/issues/17

**Comment by schmk2** [comment]
Fixed by 0c7e8041ad9629e3c8322ddb296f46d34f5647f1
