### ISSUE TITLE
Crash when quitting while the pipeline is being updated

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#24]
Steps to reproduce:

- Create a long lasting pipeline. Example:
   - Load http://www.thehistoryblog.com/wp-content/uploads/2012/03/plan_of_st_gall.jpg
   - Add a median filter with a big window size
- Enable the preview
- While the process is pending, quit the application

- The application will crash "randomly" at a number of different locations in the code
- Perhaps this could be avoided by implementing #23.

**Comment by schmk2** [comment]
Should be fixed by fbb6383ad36c0e17a29553d9f951f261ad66d092
Report back if it still happens.
