### ISSUE TITLE
Plugin generation dialog looks "squeezed down" on Linux with GTK

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#26]
"Tools > Generate Plugin Code" on my Linux system yields a Dialog with "flattened" controls (i.e. text fields and combo boxes). See attached screenshot.

![screenshot from 2015-03-26 20 25 13](https://cloud.githubusercontent.com/assets/7261570/6867107/11741008-d47f-11e4-8b65-0de6a9c8eccd.png)

**Comment by schmk2** [comment]
Window constrains were removed as of bb813ff67c366f92d9c245273cacd3d15f574f67, elements should not be squeezed anymore (tested on Mac)
