### ISSUE TITLE
Zoom in Image Viewer buggy while two images are loaded

### ISSUE THREAD

**Issue by wacki** [cpvrlab/ImagePlay#28]
If I add two images to my Image Viewer (always a loader and a binarize node in my test cases). Then the zoom behavior breaks for me. 

Below are two images that demostrate the error, in both cases I'm pressing the + icon at the top left of the Image Viewer.

**Edit**: *I should note that you have to click on both image tabs once before the bug occurs. If you add the binarize node but stay on the original image then the zoom won't break.*

### Working correctly
<a href="http://i.imgur.com/muXIEtw.gif"><img src="http://i.imgur.com/muXIEtw.gif " width="50%" /></a>

### Broken
<a href="http://i.imgur.com/5uqpu96.gif"><img src="http://i.imgur.com/5uqpu96.gif " width="50%" /></a>

### Additional note:
The zooming behaviour in general feels a little clunky sometimes, it seems like we don't zoom in to the cursor position but rather its relative position in the image frame.

**Comment by l00mi** [comment]
Award for best error description on Github ever!

**Comment by l00mi** [comment]
Award for best error description on Github ever!
