### ISSUE TITLE
Plugin development has interfacing problems

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#29]
Currently, if the interface to the IPL library changes, already compiled plugins will break. As an example, see commits 0cc65868d0dde33ab6ac698533157fd753c4b8b8 and fd4dead1561d3f6bce3fa31d22a76e9baf0cf9d9.

The problem in this case was a change in the property id enum. Because those are fixed at compile-time, the properties have to be recompiled. An alternative approach would be to use RTTI to decide the type of a property (with typeid). If that's no option, at least the propagation of changes into the plugin_development folder has to be addressed (we could use symlinks or the like).

**Comment by schmk2** [comment]
Fixed in the meantime...
