### ISSUE TITLE
Preview Window doesn't implement some default window manager behavior

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#3]
On Windows and Linux (gnome-shell) it's not possible to automatically resize the preview window using hotkeys and dragging gesture (such as dragging it from/to the upper edge of the screen to maximize it). Additionally, it's not possible on Linux to move the preview window onto another workspace without doing the same to the main window.

**Comment by schmk2** [comment]
This was actually fixed in 6.0.0 and behavior can be toggled by using "View > Show image viewer always on top"
