### ISSUE TITLE
Preview shows wrong channel names on HSL and HSV images

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#30]
Steps to reproduce:

- Load an image
- Connect it to a "Split Planes" element with "Color Model" set to HSV
- Enable the preview

- The preview will show the image channels as "RGB" regardless of the image's channel names

![channelnames](https://cloud.githubusercontent.com/assets/7261570/6918191/b100321c-d7ab-11e4-9801-b05edee23c64.png)

**Comment by schmk2** [comment]
Separate histogram channels are disabled for now (mey be implemented for a future release). Output names have been fixed.
