### ISSUE TITLE
Integrate GigE Vision Cameras

### ISSUE THREAD

**Issue by l00mi** [cpvrlab/ImagePlay#34]
Another input plug-in able to aquire images from GigE vision compatible cameras.

**Comment by mfrischknecht** [comment]
If Wikipedia and various Google results are to be believed, this could end up being quite difficult. It seems like the standard is only acquirable by licencing it from the Automated Imaging Association, and I found no open source interfaces for it.
OpenCV seems to implement interfaces to a couple of popular camera SDKs that use GigE Vision, but a generic solution also seems to be missing there. It's propably best to create plugins for specific camera SDKs once the need arises...

**Comment by l00mi** [comment]
No imminent need right know.
