### ISSUE TITLE
A view minor improvements:

### ISSUE THREAD

**Issue by hudrima1** [cpvrlab/ImagePlay#44]
- Delete of process also with backspace key (not only with delete). There is no delete key on a mac.
- Remember the last file open folder
- Write the the process name instead of "Process Settings"
- Add Back Arrow before the process name (in many browsers there is a back arrow in the top left) 
- Move Max, Min, Median, Rank Transform Operators to the Group of Morphology & Rank Order
- Reduce the minimal size of the Image Viewer so that the magnified area with all the labels underneath are still visible. The close sidebar button does not work if the magnified area overlaps.
- Give a meaning to the histogram dropdown box of the image viewer or disable it.
- Apply the same zoom level to all images in the viewer. New processes are all 1:1 and need to be zoomed separately.

**Comment by schmk2** [comment]
Everything is fixed except for:
Apply the same zoom level to all images in the viewer. New processes are all 1:1 and need to be zoomed separately.

**Comment by l00mi** [comment]
New issue with remaining enhancement. https://github.com/cpvrlab/ImagePlay/issues/58
