### ISSUE TITLE
Connecting image directly to frequency filter causes crash

### ISSUE THREAD

**Issue by JosephRedfern** [cpvrlab/ImagePlay#48]
Under Windows 8.1 x64, not tested on other platforms:

![Screenshot of crash](http://i.imgur.com/ETtKvfp.png)

Reproducible by adding a "Synthesize Image" block, and connecting it directly to a Frequency Filter block.

The (normal?) usage pattern of connecting the output of FFT to the filter works as expected.

**Comment by JosephRedfern** [comment]
Just checked, also get this issue under OS X 10.10.3.

**Comment by l00mi** [comment]
There is a fix on its way. Thanks @costypetrisor. Stay tuned!
