### ISSUE TITLE
Drag-and-drop image files to create Load Image nodes

### ISSUE THREAD

**Issue by akx** [cpvrlab/ImagePlay#50]
Would be a nice workflow improvement to be able to directly drag-and-drop supported image files onto the workspace to transform them into Load Image nodes. (Probably ditto for directories and Load Sequence.)

In the same vein, it would be nice if file-browsing inputs (such as that of Load Image) allowed drag-and-drop of files/directories onto the input box, imitating the behavior of (modern) web browsers.

**Comment by l00mi** [comment]
Makes total sense, why did we not think of that. Thanks

**Comment by schmk2** [comment]
I just added this feature. You can now drag&drop files or folders from your desktop. Tested under Windows, please report if it works on your platform.

![2015-08-07 11_42_20-imageplay 6 0 0-beta 3](https://cloud.githubusercontent.com/assets/11331299/9133246/75091e18-3cfa-11e5-906b-b27a0a961a35.png)
![2015-08-07 11_47_58-imageplay 6 0 0-beta 3](https://cloud.githubusercontent.com/assets/11331299/9133247/75093574-3cfa-11e5-85a4-2254b777c087.png)
![2015-08-07 11_48_23-imageplay 6 0 0-beta 3](https://cloud.githubusercontent.com/assets/11331299/9133248/750bd2fc-3cfa-11e5-9a24-30bbbd9d6159.png)
