### ISSUE TITLE
change demo image on imageplay website

### ISSUE THREAD

**Issue by beaugunderson** [cpvrlab/ImagePlay#59]
ImagePlay looks great but please consider changing the Lena/Lenna image used on the front page of the website. Here's some [background information](https://en.wikipedia.org/wiki/Lenna#Controversy).

**Comment by l00mi** [comment]
We got the comment already here: https://news.ycombinator.com/item?id=10010534

In general we are all against gender stereotypes, especially we need more women in CS. We are just no sure if this is really the problem on this matter. I spoke with multiple women in CS working in the field of Image Processing which are not offended at all by the use of Lenna in this context. Somehow nobody does complain about the use of [David](http://graphics.stanford.edu/papers/dmich-sig00/) in 3d scans .. ?

We will discuss in this in the group and consider your comment.

**Comment by beaugunderson** [comment]
While the image may not be offensive among people already familiar with it because they're in the field of image processing I still think it's important to consider how it affects others (including potential entrants to the field) and how it perpetuates the "male gaze". Thank you for you agreeing to consider it. :sparkles:

**Comment by l00mi** [comment]
This took some time now. We discussed this internally and decided it is better to clarify why we use Lena (with a small caption) than to create a taboo around the picture. If you have further questions please come back to us!

**Comment by beaugunderson** [comment]
This is a very disappointing outcome.

**Comment by neauoire** [comment]
It is indeed.

**Comment by beaugunderson** [comment]
Maybe it's [time to reconsider](https://t.co/4BAzYowFmu)?
