### ISSUE TITLE
Add examples to toy around for beginners.

### ISSUE THREAD

**Issue by l00mi** [cpvrlab/ImagePlay#63]
https://news.ycombinator.com/item?id=10012636

**Comment by fabiopedrosa** [comment]
This would be very helpful!

**Comment by l00mi** [comment]
We plan to release 6.0.0 final in the near future, that said we will have some examples delivered.

**Comment by fabiopedrosa** [comment]
Could you help me with something in the meanwhile?

How can I learn/deduce which input can be connected to each element? 
For instance, I'm applying a sobel operator to my gray image, but then I can't split its two places, or apply a blur to the resulting image. What am I doing wrong?

**Comment by l00mi** [comment]
This is a not yet solved problem. We need to look into that with #86.

Your example does not work as the sobel operator outputs as you say two planes. We have no process yet to choose one plane. So you do everything right! It's just not yet possible. (-,

**Comment by schmk2** [comment]
I added a few things for you, see #86

**Comment by l00mi** [comment]
Examples are delivered with final version.
