### ISSUE TITLE
Pressing DEL on Windows to delete nodes frequently causes it to crash.

### ISSUE THREAD

**Issue by THofstee** [cpvrlab/ImagePlay#69]

**Comment by l00mi** [comment]
Thank you for the  bug description. Do you have details about when it crashes? What does mean frequently?

**Comment by schmk2** [comment]
Might have been fixed by e35619def098b40fe2c76974c9eee4ff941ec86e which will be released in Beta.4

**Comment by l00mi** [comment]
Tested, seems to be fixed in ImagePlay 6.0.0-beta.4. Please reopen issue if the reported error still remains.
