### ISSUE TITLE
Edges get removed on reload

### ISSUE THREAD

**Issue by l00mi** [cpvrlab/ImagePlay#72]
The additional checks introduced with pull request https://github.com/cpvrlab/ImagePlay/pull/54 now remove edges in the loading process due timing issues.

Either we hack it by disabling the check temporarily while loading, or we find a way to load the processes in the correct order to satisfy the checks.

**Comment by schmk2** [comment]
fixed by 210d9f82e2100e4825998e5c22edfebaefaef5ee, we will need to look into the input/output validation again later...
