### ISSUE TITLE
Segfault while closing app

### ISSUE THREAD

**Issue by ladotonia** [cpvrlab/ImagePlay#74]
Running in Linux with an Image viewer open with two tabs zoomed in, a seg fault is thrown when exiting the application.  The delete triggers a call to update the scrollbar location in IPImageViewer which calls ImageViewerWindow::on_horizontalScrollBarChanged() and segfaults on the map iterator.

A simple fix would be to disconnect the signals in the destructor on IPImageViewer.

**Comment by schmk2** [comment]
Fixed by 044ae01f8f0bea96d1a2d76b8219907e3fdcccc1

Please report back if it still happens...
