### ISSUE TITLE
Application crashes if it gets closed with an active webcam element

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#8]
Reproduction:

- Create a "Capture Camera" element
- Enable the preview
- Close the application

- The application causes a Segfault (Linux)
- Proposition: Automatically pause the preview before closing the application

Stacktrace:
0	ImageViewerWindow::updateImage	ImageViewerWindow.cpp	152	0x421758	
1	IPProcessGrid::execute	IPProcessGrid.cpp	305	0x43b7b9	
2	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
3	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
4	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
5	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
6	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
7	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
8	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
9	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
10	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
11	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
12	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
13	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
14	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
15	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
16	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
17	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
18	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
19	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
20	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
21	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
22	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
23	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
24	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
25	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
26	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
27	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
28	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
29	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
30	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
31	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
32	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
33	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
34	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
35	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
36	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
37	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
38	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
39	IPProcessGrid::execute	IPProcessGrid.cpp	345	0x43b9ab	
40	MainWindow::execute	MainWindow.cpp	820	0x46edf3	
41	MainWindow::qt_static_metacall	moc_MainWindow.cpp	200	0x48f28b	
42	QMetaObject::activate(QObject*, int, int, void**)	/usr/lib/libQt5Core.so.5		0x7ffff5ab8309	
43	QTimer::timerEvent(QTimerEvent*)	/usr/lib/libQt5Core.so.5		0x7ffff5ac6108	
44	QObject::event(QEvent*)	/usr/lib/libQt5Core.so.5		0x7ffff5ab9023	
45	QApplicationPrivate::notify_helper(QObject*, QEvent*)	/usr/lib/libQt5Widgets.so.5		0x7ffff636eacc	
46	QApplication::notify(QObject*, QEvent*)	/usr/lib/libQt5Widgets.so.5		0x7ffff6373f10	
47	QCoreApplication::notifyInternal(QObject*, QEvent*)	/usr/lib/libQt5Core.so.5		0x7ffff5a87d1b	
48	QTimerInfoList::activateTimers()	/usr/lib/libQt5Core.so.5		0x7ffff5adef6d	
49	??	/usr/lib/libQt5Core.so.5		0x7ffff5adf3b1	
50	g_main_context_dispatch	/usr/lib/libglib-2.0.so.0		0x7ffff2e3871d	
51	??	/usr/lib/libglib-2.0.so.0		0x7ffff2e38a08	
52	g_main_context_iteration	/usr/lib/libglib-2.0.so.0		0x7ffff2e38abc	
53	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)	/usr/lib/libQt5Core.so.5		0x7ffff5ae0077	
54	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)	/usr/lib/libQt5Core.so.5		0x7ffff5a857b2	
55	QCoreApplication::exec()	/usr/lib/libQt5Core.so.5		0x7ffff5a8d18c	
56	main	main.cpp	67	0x465362

**Comment by schmk2** [comment]
Fixed by cd7187583a9b72691c640213bac6e2e3df72c5a3

Must be tested on Linux and OS X

**Comment by l00mi** [comment]
tested on OS X, works.
