### ISSUE TITLE
build

### ISSUE THREAD

**Issue by twosilly-2B** [cpvrlab/ImagePlay#96]
Hello, I am a novice!

I recently in image recognition are very interested in your software to exercise your own! 
I'm going to compile it! In the qt5.7windows7 environment, 
the results I was wrong! I can't solve hope you can give me the answer! Thank you!

![image](https://cloud.githubusercontent.com/assets/21135628/20388274/0aacf730-acff-11e6-8f57-dc7dd32b6619.png)
This is my fault!

**Comment by schmk2** [comment]
We have not tested with Qt 5.7 yet. Some advise:
1) Have you cloned recursively as described here: https://github.com/cpvrlab/ImagePlay/blob/develop/install.md
2) Try to switch to the "develop" branch for our newest changes: `git checkout develop`
