### ISSUE TITLE
Plugin Debug C++ error

### ISSUE THREAD

**Issue by Melih01** [cpvrlab/ImagePlay#98]
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error (active)	E0322	object of abstract class type "NormalMap" is not allowed:	NormalMap	..\ImagePlay-6.1.0\plugin_development\NormalMap\NormalMap.h   35  pure virtual function "IPLProcess::processInputData" has no overrider

-Severity	Code	Description	Project	File	Line	Suppression State
Error	C2259	'NormalMap': cannot instantiate abstract class	NormalMap	..\imageplay-6.1.0\plugin_development\normalmap\NormalMap.h	35	

Problem this code "  IPLProcess* create()    { return new NormalMap(); } "

How can I fix this error?

```
#ifndef NormalMap_H
#define NormalMap_H

#include "IPL_global.h"
#include "IPLProcess.h"


/*!
 * \ The process
 */

class NormalMap : public IPLClonableProcess<NormalMap>
{
public:
    NormalMap() : IPLClonableProcess() { init(); }
    ~NormalMap()  { destroy(); }

    void init();
    void destroy();
    bool processInputData(IPLImage* image, int, bool useOpenCV);
    IPLData* getResultData(int);

private:
    IPLImage*  _result;
};

/*!
 * \The plugin container class
 */
class NormalMapDriver : public IPLProcessDriver
{
public:
    NormalMapDriver() : IPLProcessDriver("NormalMapDriver", NormalMap::version) {}

    IPLProcess* create()    { return new NormalMap(); }
    std::string className() { return "NormalMap"; }
    std::string author()    { return "Melih"; }
    int         version()   { return 1; }
};
#endif // NormalMap_H
```

**Comment by mawapo** [comment]
FIXED:

I did have same error and could resolve by fixing IPLProcess.h in the following way:

l.137:       virtual bool            processInputData            (IPLData*, int, bool) = 0;
changed to:
l.137:       virtual bool            processInputData            (IPLImage*, int, bool) = 0;

Obviously there is a mangling between IPLData* and (correct) IPLImage*

However I still get runtime errors in debug mode while release works fine for me (VS2017).
I will throw in other thread in this forum.
